// Generated file do not edit, generated by io.requery.processor.EntityProcessor
package in.dc297.mqttclpro.entity;

import io.requery.meta.EntityModel;
import io.requery.meta.EntityModelBuilder;

public class Models {
    public static final EntityModel DEFAULT = new EntityModelBuilder("default")
            .addType(BrokerEntity.$TYPE)
            .addType(MessageEntity.$TYPE)
            .addType(TopicEntity.$TYPE)
            .build();

    private Models() {
    }
}
